### ISSUE TITLE
Please, publish last version on npm

### ISSUE THREAD

**Issue by bautrukevich** [Nijikokun/minami#28]
Mixed Content: The page at 'index.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Montserrat:400,700'. This request has been blocked; the content must be served over HTTPS.

Because in repo stylesheet is linked by https. In npm package stylesheet is linked by http.

Thank's.

**Comment by nijikokun** [comment]
I've published `1.2.0` :tada:
